spring.application.name=restro-onboarding-BE
spring.datasource.url=jdbc:mysql://localhost:3306/restro
spring.datasource.username=root
spring.datasource.password=Pramod.21
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true